-- phpMyAdmin SQL Dump
-- version 4.7.0
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 07-06-2018 a las 03:35:18
-- Versión del servidor: 5.7.17
-- Versión de PHP: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `pruebas`
--

DELIMITER $$
--
-- Procedimientos
--
CREATE DEFINER=`root`@`localhost` PROCEDURE `obtenerSitios` ()  NO SQL
SELECT * FROM sitios$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_registrar_usuario` (IN `email_` VARCHAR(60), IN `password_` VARCHAR(30), IN `nombre_` VARCHAR(30), IN `edad_` INT, IN `genero_` VARCHAR(1))  INSERT INTO `usuario`(`email`, `nombre`, `edad`, `genero`, `password`) VALUES(email_,nombre_,edad_,genero_,password_)$$

DELIMITER ;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `sitios`
--

CREATE TABLE `sitios` (
  `precio` varchar(25) NOT NULL,
  `ubicacion` varchar(25) NOT NULL,
  `tipo_viaje` varchar(25) NOT NULL,
  `descripcion` varchar(1000) NOT NULL,
  `titulo` varchar(500) NOT NULL,
  `latitud` varchar(25) DEFAULT NULL,
  `longitud` varchar(25) DEFAULT NULL,
  `id` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `sitios`
--

INSERT INTO `sitios` (`precio`, `ubicacion`, `tipo_viaje`, `descripcion`, `titulo`, `latitud`, `longitud`, `id`) VALUES
('100-1000', 'Rural', 'Cultural', ' El Monumento Nacional Guayabo es un área protegida de Costa Rica, conocida principalmente porque en ella se encuentra uno de los sitios arqueológicos prehispánicos más antiguos e importantes del país.', 'Monumento nacional Guayabo', '9.970865', '-83.690761', 1),
('100-1000', 'Urbano', 'Familiar', 'El parque quesada casal es el parque central de Turrialba donde niños y adultos pueden convivir con la naturaleza y disfrutar de la misma.', 'Parque Quesada Casal', '9.906569', '-83.684173', 2),
('100-1000', 'Urbano', 'Familiar', 'El jardín botánico del catie es un sitio donde usted puede venir y apreciar la flora del lugar y tener un momento agradable con sus acompañantes.', 'Jardín Botánico CATIE', '9.900730', '-83.668591', 3),
('100-1000', 'Urbano', 'Cultural', 'El Museo de Turrialba Omar Salazar fue creado el 10 de noviembre de 1995, ocupa un edificio declarado Patrimonio Histórico - Arquitectónico, el museo pretende rescatar las raíces indígenas del cantón, cuenta con una exhibición arqueológica mostrando los modos de vida de las primeras poblaciones de Turrialba.', 'Museo Omar Salazar Obando', '9.901629', '-83.672596', 4),
('5001-15000', 'Rural', 'Deportivo', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Río Turrialba', '9.923579', '-83.697948', 5),
('5001-15000', 'Urbano', 'Negocio', 'Desde los platillos hasta la atención, no hay ninguna queja. Quizá los precios un poco altos. El rice and beans estaba excelente, y el filete de corvina empanizado en salsa marinara muy bueno. Tienen un buen surtido de cervezas importadas y artesanales.', 'Rio restaurant', '9.917153', '-83.691253', 6),
('100-1000', 'Rural', 'Familiar', 'Este lugar básicamente nos teletransporta a otra época, donde realmente se vivía del café, así que, si quiere explorar y vegetar luego de la catarata, este es el lugar ideal. Al final terminamos almorzando en la sodita Torre Alba', 'Catarata de aquiares', '9.933508', '-83.720895', 7),
('1001-5000', 'Rural', 'Negocio', 'Este sitio muestra cómo está conformada la represa hidroeléctrica de angostura ubicada en Turrialba', 'Embalse Angostura', '9.857625', '-83.648223', 8),
('5001-15000', 'Rural', 'Negocio', 'Hacienda Sitio de Mata le permitirá disfrutar de su evento rodeado de vistas maravillosas al Valle de Turrialba. Con un salón con una capacidad de 200 personas', 'Hacienda Sitio de Mata', '9.880187', '-83.626254', 9),
('5001-15000', 'Rural', 'Negocio', 'Un verdadero tour de café, con un experto en el tema y recorrido por la plantación y la industrialización', 'Golden Bean Coffee Tour', '9.837224', '-83.650246', 10),
('1001-5000', 'Rural', 'Familiar', 'Es un ambiente sano para la familia, cuenta con gran espacio por tanto el aburrimiento no abrirá paso y además del excelente servicio y comidas deliciosas', 'Centro Recreativo San Martin', '9.934907', '-83.653348', 11),
('1001-5000', 'Rural', 'Familiar', 'El volcán Turrialba es un estratovolcán complejo activo de Costa Rica, ubicado en el distrito de Santa Cruz, en el cantón de Turrialba, provincia de Cartago, a 24 km de la ciudad del mismo nombre. Es el más oriental de los volcanes de la cordillera Volcánica Central, y da nombre al Parque nacional que le envuelve, el Parque nacional Volcán Turrialba.', 'Volcán Turrialba', '10.017477', '-83.764836', 12),
('1001-5000', 'Urbano', 'Cultural', 'Este lugar albergó a enfermos que padecían de tuberculosis, dejó de ser un centro médico en 1963, en el lugar murieron muchas personas, por lo que las leyendas de miedo han hecho que muchas personas visiten constantemente el lugar.', 'Sanatorio Dúran', '9.932173', '-83.879251', 13),
('100-1000', 'Rural', 'Deportivo', 'En este lugar podrá caminar por sus extensos senderos, mientras disfruta de la vegetación boscosa y sus mariposario.', 'Parque Ambiental Río Loro', '9.909125', '-83.943672', 14),
('100-1000', 'Urbano', 'Familiar', 'La vista en este lugar lo va a enamorar, además podrá disfrutar de las zonas verdes  y las áreas de pic nic, Ujarras, Cachí y sus alrededores son algunos lugares que podrá observar desde aquí.', 'Mirador de Ujarras', '9.836997', '-83.841373', 15),
('100-1000', 'Urbano', 'Familiar', 'Este mirador es una excelente opción para relajarse, en la cual podrá observar todo el valle de Orosí', 'Mirador de Orosi', '9.818680', '-83.858569', 16),
('100-1000', 'Rural', 'Cultural', 'Acá se encuentra el volcán más alto del país con una altura de 3.431 m.s.n.s, una de sus atracciones además del volcán, es que cuando el clima está despejado se logra ver parte del el océano Pacífico y el Atlántico', 'Parque Nacional Volcán Irazú', '9.980185', '-83.849114', 17),
('100-1000', 'Rural', 'Familiar', 'Este bosque forma parte del Parque Nacional Volcan Irazú, en este lugar podrá disfrutar de 16 km de senderos en los cuales podrá caminar, además de las zonas de pic nic, en las cuales podrá descansar y aprovechar su abundante vegetación como el bosque de eucalipto y el de pinos, para tomar fotografías.', 'Bosque Prusia', '9.954646', '-83.881439', 18),
('100-1000', 'Urbano', 'Cultural', 'Las conocidas Ruinas de Ujarrás se encuentran en la comunidad del mismo nombre. El principal atractivo turístico del lugar son las ruinas de la Iglesia de Nuestra Señora de la Limpia Concepción. El sitio cuenta con amplias zonas verdes, mesas para pic nic, ranchos y servicios sanitarios', 'Ruinas de Ujarrás', '9.827779', '-83.836266', 19),
('5001-15000', 'Rural', 'Negocio', 'Excelente lugar, la comida es muy buena y atienden cada petición que se hace y los empleados son muy amables! Perfecto para llegar a desayunar o almorzar durante un viaje de amigos o en familia.', 'Casa Turire', '9.862364', '-83.645292', 20),
('5001-15000', 'Rural', 'Negocio', 'Hermosa vista de la campiña turrialbeña y del proyecto hidroeléctrico. La comida es buena, y ambiente tranquilo.', 'Turrialtico', '9.894619', '-83.639800', 21),
('5001-15000', 'Urbano', 'Negocio', 'Rápida atención, deliciosos bocadillos, es un lugar pequeño, pero la carne muy suave. Recomendado para cuándo va de paso', 'Betico mata', '9.903420', '-83.681609', 22),
('5001-15000', 'Urbano', 'Negocio', 'Su énfasis es comida muy casera, fundamentalmente para personas que trabajan, viajan o estudian. Buena atención, buen servicio y buena comida.', 'Soda la u', '9.900898', '-83.674199', 23),
('5001-15000', 'Urbano', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Maracuya', '9.907969', '-83.686680', 24),
('5001-15000', 'Urbano', 'Negocio', 'El Hotel Wagelia Turrialba se encuentra en Turrialba, a 43 km de San José y a 50 km de Escazú. Ofrece un restaurante, WiFi y aparcamiento privado, ambos gratuitos.', 'Hotel Wagelia Turrialba', '9.904854', '-83.685726', 25),
('5001-15000', 'Rural', 'Negocio', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'La Cascada', '9.944652', '-83.704463', 26),
('5001-15000', 'Rural', 'Negocio', 'La Hacienda Monteclaro es una granja agrícola y ecológica situada a 10 minutos del centro de Turrialba. Cada cubierta ecológica disfruta de vistas del valle de Turrialba y su volcán. Todas incluyen mosquiteras para cada cama, baño y terraza. Hay lámparas solares y velas en jarrones.', 'Hacienda monte carlo', '9.896939', '-83.637368', 27),
('5001-15000', 'Rural', 'Negocio', 'El establecimiento Casa Aquiares Lodge está ubicado en Turrialba y tiene jardín con piscina exterior. La ciudad de San José se halla a 39 km. Hay WiFi gratuita en todas las dependencias.', 'Aquiares lodge', '9.935795', '-83.720813', 28),
('5001-15000', 'Rural', 'Negocio', 'El Bella Vista Ranch está situado en Turrialba, en la provincia de Cartago, a 13 km de Santa Cruz, y cuenta con 2 piscinas al aire libre, una de ellas abierta todo el año. Alberga un bar y ofrece aparcamiento privado gratuito.', 'Bella vista', '9.929817', '-83.617673', 29),
('5001-15000', 'Urbano', 'Negocio', 'El Wagelia Espino Blanco Lodge dispone de solárium y vistas a la montaña y está situado en Turrialba, Cartago, a 43 km de San José. El establecimiento se encuentra a 49 km de Escazú. Se proporciona WiFi gratuita', 'Espino blanco lodge', '9.945925', '-83.690184', 30),
('5001-15000', 'Urbano', 'Negocio', 'El Hotel Villa Florencia está situado en Cartago, a 20 km de San José, y ofrece piscina al aire libre y vistas a la montaña. Este establecimiento alberga bar y facilita WiFi gratuita y aparcamiento privado, también gratuito.', 'Hotel villa Florencia', '9.873677', '-83.659176', 31),
('5001-15000', 'Rural', 'Negocio', 'El Green Mountain and Lodge se encuentra a solo 2,5 km de la ciudad de Turrialba, en la región de Cartago, a 300 metros al norte de la residencia de ancianos de la carretera San Juan Norte.', 'Green mountain', '9.897479', '-83.697618', 32),
('5001-15000', 'Urbano', 'Negocio', 'Este albergue tropical se ubica a 5 minutos en coche del centro de Turrialba y ofrece conexión Wi-Fi y aparcamiento gratuitos. También alberga una cocina compartida y una terraza con hamacas.', 'Spanish by the river', '9.749042', '-83.753451', 33),
('5001-15000', 'Urbano', 'Negocio', 'El Pacuare Outdoor Center, que tiene terraza y vistas a la montaña, se encuentra en Turrialba, en la región de Cartago, a 20 km de Santa Cruz.', 'Pacuare outdoor', '9.988160', '-83.570572', 34),
('5001-15000', 'Rural', 'Negocio', 'With mountain views, Eco Villa Turri is located in Turrialba and has free WiFi. Each unit is fitted with a fully equipped kitchen with a dishwasher, a seating area with a sofa, a flat-screen TV and a private bathroom with shower. An oven and toaster are also provided, as well as a kettle.', 'Eco villa turri', '9.947724', '-83.695672', 35),
('1001-5000', 'Rural', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Eco villa turri2', '9.934907', '-83.704463', 36),
('5001-15000', 'Urbano', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '10.017477', '-83.650246', 37),
('1001-5000', 'Rural', 'Deportivo', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '9.900898', '-83.695672', 38),
('5001-15000', 'Urbano', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.988160', '-83.704463', 39),
('1001-5000', 'Urbano', 'Negocio', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '9.934907', '-83.704463', 40),
('1001-5000', 'Rural', 'Cultural', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '10.017477', '-83.690184', 41),
('5001-15000', 'Rural', 'Negocio', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Río Turrialba2', '9.988160', '-83.695672', 42),
('5001-15000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Rio restaurant2', '9.934907', '-83.841373', 43),
('1001-5000', 'Urbano', 'Negocio', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '9.934907', '-83.690184', 44),
('1001-5000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '10.017477', '-83.650246', 45),
('5001-15000', 'Urbano', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '9.988160', '-83.650246', 46),
('5001-15000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Rio restaurant2', '9.934907', '-83.704463', 47),
('100-1000', 'Urbano', 'Deportivo', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Rio restaurant2', '9.934907', '-83.650246', 48),
('100-1000', 'Rural', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '10.017477', '-83.695672', 49),
('100-1000', 'Urbano', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Eco villa turri2', '10.017477', '-83.695672', 50),
('100-1000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '9.880187', '-83.690184', 51),
('1001-5000', 'Rural', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Catarata de aquiares2', '9.900898', '-83.650246', 52),
('5001-15000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Río Turrialba2', '9.880187', '-83.695672', 53),
('5001-15000', 'Rural', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Hacienda monte carlo2', '9.988160', '-83.704463', 54),
('100-1000', 'Urbano', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Río Turrialba2', '9.988160', '-83.704463', 55),
('5001-15000', 'Rural', 'Deportivo', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Rio restaurant2', '9.988160', '-83.841373', 56),
('100-1000', 'Urbano', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '9.934907', '-83.704463', 57),
('100-1000', 'Urbano', 'Negocio', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Hacienda monte carlo2', '9.988160', '-83.695672', 58),
('1001-5000', 'Rural', 'Familiar', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Río Turrialba2', '9.900898', '-83.690184', 59),
('100-1000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Catarata de aquiares2', '9.880187', '-83.841373', 60),
('100-1000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Catarata de aquiares2', '10.017477', '-83.650246', 61),
('100-1000', 'Urbano', 'Familiar', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '9.988160', '-83.704463', 62),
('1001-5000', 'Urbano', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '9.934907', '-83.704463', 63),
('5001-15000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Hacienda monte carlo2', '9.900898', '-83.841373', 64),
('1001-5000', 'Urbano', 'Cultural', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '10.017477', '-83.841373', 65),
('100-1000', 'Urbano', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Sanatorio Dúran2', '9.934907', '-83.695672', 66),
('1001-5000', 'Urbano', 'Negocio', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.934907', '-83.704463', 67),
('5001-15000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Río Turrialba2', '9.988160', '-83.650246', 68),
('1001-5000', 'Urbano', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.900898', '-83.841373', 69),
('100-1000', 'Rural', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '9.880187', '-83.695672', 70),
('5001-15000', 'Urbano', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Catarata de aquiares2', '9.880187', '-83.695672', 71),
('1001-5000', 'Rural', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.900898', '-83.695672', 72),
('1001-5000', 'Rural', 'Deportivo', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Rio restaurant2', '9.880187', '-83.841373', 73),
('100-1000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Rio restaurant2', '9.988160', '-83.690184', 74),
('5001-15000', 'Rural', 'Negocio', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.934907', '-83.695672', 75),
('100-1000', 'Urbano', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Rio restaurant2', '9.880187', '-83.690184', 76),
('5001-15000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Rio restaurant2', '9.934907', '-83.841373', 77),
('100-1000', 'Urbano', 'Familiar', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Río Turrialba2', '9.988160', '-83.695672', 78),
('5001-15000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Hacienda monte carlo2', '9.880187', '-83.650246', 79),
('5001-15000', 'Urbano', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Hacienda monte carlo2', '9.880187', '-83.695672', 80),
('1001-5000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Rio restaurant2', '9.880187', '-83.695672', 81),
('1001-5000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.900898', '-83.841373', 82),
('1001-5000', 'Urbano', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Hacienda monte carlo2', '9.900898', '-83.841373', 83),
('1001-5000', 'Rural', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '9.880187', '-83.690184', 84),
('100-1000', 'Urbano', 'Deportivo', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '9.988160', '-83.841373', 85),
('1001-5000', 'Rural', 'Negocio', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '9.988160', '-83.841373', 86),
('100-1000', 'Urbano', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Eco villa turri2', '9.988160', '-83.690184', 87),
('100-1000', 'Urbano', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '9.880187', '-83.695672', 88),
('100-1000', 'Urbano', 'Deportivo', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Sanatorio Dúran2', '10.017477', '-83.695672', 89),
('100-1000', 'Rural', 'Cultural', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '9.988160', '-83.704463', 90),
('5001-15000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '10.017477', '-83.690184', 91),
('5001-15000', 'Urbano', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Rio restaurant2', '9.988160', '-83.690184', 92),
('1001-5000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.900898', '-83.690184', 93),
('1001-5000', 'Urbano', 'Deportivo', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '9.988160', '-83.704463', 94),
('5001-15000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Río Turrialba2', '9.934907', '-83.841373', 95),
('100-1000', 'Urbano', 'Deportivo', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.880187', '-83.841373', 96),
('100-1000', 'Urbano', 'Familiar', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Hacienda monte carlo2', '9.880187', '-83.650246', 97),
('5001-15000', 'Rural', 'Deportivo', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.988160', '-83.704463', 98),
('100-1000', 'Urbano', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '10.017477', '-83.841373', 99),
('1001-5000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Catarata de aquiares2', '9.988160', '-83.650246', 100),
('100-1000', 'Urbano', 'Familiar', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '9.988160', '-83.841373', 101),
('1001-5000', 'Urbano', 'Deportivo', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Río Turrialba2', '9.880187', '-83.690184', 102),
('1001-5000', 'Rural', 'Familiar', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '9.880187', '-83.690184', 103),
('100-1000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Rio restaurant2', '9.988160', '-83.695672', 104),
('1001-5000', 'Urbano', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Rio restaurant2', '10.017477', '-83.650246', 105),
('100-1000', 'Rural', 'Negocio', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Río Turrialba2', '9.900898', '-83.841373', 106),
('1001-5000', 'Rural', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Hacienda monte carlo2', '10.017477', '-83.650246', 107),
('1001-5000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.988160', '-83.690184', 108),
('5001-15000', 'Urbano', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Hacienda monte carlo2', '9.900898', '-83.704463', 109),
('5001-15000', 'Rural', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.900898', '-83.841373', 110),
('5001-15000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.934907', '-83.650246', 111),
('1001-5000', 'Urbano', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Río Turrialba2', '10.017477', '-83.841373', 112),
('5001-15000', 'Rural', 'Cultural', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '9.900898', '-83.650246', 113),
('100-1000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Rio restaurant2', '9.988160', '-83.650246', 114),
('100-1000', 'Urbano', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Catarata de aquiares2', '9.934907', '-83.695672', 115),
('100-1000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Catarata de aquiares2', '9.900898', '-83.690184', 116),
('5001-15000', 'Urbano', 'Negocio', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '9.880187', '-83.650246', 117),
('5001-15000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Rio restaurant2', '10.017477', '-83.704463', 118),
('5001-15000', 'Rural', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Catarata de aquiares2', '9.900898', '-83.704463', 119),
('5001-15000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.988160', '-83.650246', 120),
('5001-15000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.880187', '-83.841373', 121),
('5001-15000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.988160', '-83.690184', 122),
('5001-15000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.934907', '-83.690184', 123),
('1001-5000', 'Urbano', 'Deportivo', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Catarata de aquiares2', '9.934907', '-83.690184', 124),
('100-1000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.934907', '-83.650246', 125),
('1001-5000', 'Rural', 'Familiar', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '10.017477', '-83.650246', 126),
('1001-5000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Rio restaurant2', '9.880187', '-83.690184', 127),
('1001-5000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '10.017477', '-83.690184', 128),
('100-1000', 'Urbano', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Rio restaurant2', '9.880187', '-83.695672', 129),
('5001-15000', 'Rural', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '9.900898', '-83.650246', 130),
('100-1000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Hacienda monte carlo2', '10.017477', '-83.650246', 131),
('100-1000', 'Urbano', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Catarata de aquiares2', '9.934907', '-83.690184', 132),
('1001-5000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.988160', '-83.690184', 133),
('1001-5000', 'Urbano', 'Negocio', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.934907', '-83.690184', 134),
('5001-15000', 'Urbano', 'Deportivo', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Catarata de aquiares2', '9.880187', '-83.704463', 135),
('1001-5000', 'Rural', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Eco villa turri2', '9.934907', '-83.704463', 136),
('5001-15000', 'Urbano', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '10.017477', '-83.650246', 137),
('1001-5000', 'Rural', 'Deportivo', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '9.900898', '-83.695672', 138),
('5001-15000', 'Urbano', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.988160', '-83.704463', 139),
('1001-5000', 'Urbano', 'Negocio', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '9.934907', '-83.704463', 140),
('1001-5000', 'Rural', 'Cultural', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '10.017477', '-83.690184', 141),
('5001-15000', 'Rural', 'Negocio', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Río Turrialba2', '9.988160', '-83.695672', 142),
('5001-15000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Rio restaurant2', '9.934907', '-83.841373', 143),
('1001-5000', 'Urbano', 'Negocio', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '9.934907', '-83.690184', 144),
('1001-5000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '10.017477', '-83.650246', 145),
('5001-15000', 'Urbano', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '9.988160', '-83.650246', 146),
('5001-15000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Rio restaurant2', '9.934907', '-83.704463', 147),
('100-1000', 'Urbano', 'Deportivo', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Rio restaurant2', '9.934907', '-83.650246', 148),
('100-1000', 'Rural', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '10.017477', '-83.695672', 149),
('100-1000', 'Urbano', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Eco villa turri2', '10.017477', '-83.695672', 150);
INSERT INTO `sitios` (`precio`, `ubicacion`, `tipo_viaje`, `descripcion`, `titulo`, `latitud`, `longitud`, `id`) VALUES
('100-1000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '9.880187', '-83.690184', 151),
('1001-5000', 'Rural', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Catarata de aquiares2', '9.900898', '-83.650246', 152),
('5001-15000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Río Turrialba2', '9.880187', '-83.695672', 153),
('5001-15000', 'Rural', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Hacienda monte carlo2', '9.988160', '-83.704463', 154),
('100-1000', 'Urbano', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Río Turrialba2', '9.988160', '-83.704463', 155),
('5001-15000', 'Rural', 'Deportivo', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Rio restaurant2', '9.988160', '-83.841373', 156),
('100-1000', 'Urbano', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '9.934907', '-83.704463', 157),
('100-1000', 'Urbano', 'Negocio', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Hacienda monte carlo2', '9.988160', '-83.695672', 158),
('1001-5000', 'Rural', 'Familiar', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Río Turrialba2', '9.900898', '-83.690184', 159),
('100-1000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Catarata de aquiares2', '9.880187', '-83.841373', 160),
('100-1000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Catarata de aquiares2', '10.017477', '-83.650246', 161),
('100-1000', 'Urbano', 'Familiar', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '9.988160', '-83.704463', 162),
('1001-5000', 'Urbano', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '9.934907', '-83.704463', 163),
('5001-15000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Hacienda monte carlo2', '9.900898', '-83.841373', 164),
('1001-5000', 'Urbano', 'Cultural', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '10.017477', '-83.841373', 165),
('100-1000', 'Urbano', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Sanatorio Dúran2', '9.934907', '-83.695672', 166),
('1001-5000', 'Urbano', 'Negocio', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.934907', '-83.704463', 167),
('5001-15000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Río Turrialba2', '9.988160', '-83.650246', 168),
('1001-5000', 'Urbano', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.900898', '-83.841373', 169),
('100-1000', 'Rural', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '9.880187', '-83.695672', 170),
('5001-15000', 'Urbano', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Catarata de aquiares2', '9.880187', '-83.695672', 171),
('1001-5000', 'Rural', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.900898', '-83.695672', 172),
('1001-5000', 'Rural', 'Deportivo', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Rio restaurant2', '9.880187', '-83.841373', 173),
('100-1000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Rio restaurant2', '9.988160', '-83.690184', 174),
('5001-15000', 'Rural', 'Negocio', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.934907', '-83.695672', 175),
('100-1000', 'Urbano', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Rio restaurant2', '9.880187', '-83.690184', 176),
('5001-15000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Rio restaurant2', '9.934907', '-83.841373', 177),
('100-1000', 'Urbano', 'Familiar', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Río Turrialba2', '9.988160', '-83.695672', 178),
('5001-15000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Hacienda monte carlo2', '9.880187', '-83.650246', 179),
('5001-15000', 'Urbano', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Hacienda monte carlo2', '9.880187', '-83.695672', 180),
('1001-5000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Rio restaurant2', '9.880187', '-83.695672', 181),
('1001-5000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.900898', '-83.841373', 182),
('1001-5000', 'Urbano', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Hacienda monte carlo2', '9.900898', '-83.841373', 183),
('1001-5000', 'Rural', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '9.880187', '-83.690184', 184),
('100-1000', 'Urbano', 'Deportivo', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '9.988160', '-83.841373', 185),
('1001-5000', 'Rural', 'Negocio', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '9.988160', '-83.841373', 186),
('100-1000', 'Urbano', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Eco villa turri2', '9.988160', '-83.690184', 187),
('100-1000', 'Urbano', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '9.880187', '-83.695672', 188),
('100-1000', 'Urbano', 'Deportivo', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Sanatorio Dúran2', '10.017477', '-83.695672', 189),
('100-1000', 'Rural', 'Cultural', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '9.988160', '-83.704463', 190),
('5001-15000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '10.017477', '-83.690184', 191),
('5001-15000', 'Urbano', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Rio restaurant2', '9.988160', '-83.690184', 192),
('1001-5000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.900898', '-83.690184', 193),
('1001-5000', 'Urbano', 'Deportivo', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '9.988160', '-83.704463', 194),
('5001-15000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Río Turrialba2', '9.934907', '-83.841373', 195),
('100-1000', 'Urbano', 'Deportivo', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.880187', '-83.841373', 196),
('100-1000', 'Urbano', 'Familiar', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Hacienda monte carlo2', '9.880187', '-83.650246', 197),
('5001-15000', 'Rural', 'Deportivo', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.988160', '-83.704463', 198),
('100-1000', 'Urbano', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '10.017477', '-83.841373', 199),
('1001-5000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Catarata de aquiares2', '9.988160', '-83.650246', 200),
('100-1000', 'Urbano', 'Familiar', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '9.988160', '-83.841373', 201),
('1001-5000', 'Urbano', 'Deportivo', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Río Turrialba2', '9.880187', '-83.690184', 202),
('1001-5000', 'Rural', 'Familiar', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '9.880187', '-83.690184', 203),
('100-1000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Rio restaurant2', '9.988160', '-83.695672', 204),
('1001-5000', 'Urbano', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Rio restaurant2', '10.017477', '-83.650246', 205),
('100-1000', 'Rural', 'Negocio', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Río Turrialba2', '9.900898', '-83.841373', 206),
('1001-5000', 'Rural', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Hacienda monte carlo2', '10.017477', '-83.650246', 207),
('1001-5000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.988160', '-83.690184', 208),
('5001-15000', 'Urbano', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Hacienda monte carlo2', '9.900898', '-83.704463', 209),
('5001-15000', 'Rural', 'Familiar', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.900898', '-83.841373', 210),
('5001-15000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.934907', '-83.650246', 211),
('1001-5000', 'Urbano', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Río Turrialba2', '10.017477', '-83.841373', 212),
('5001-15000', 'Rural', 'Cultural', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '9.900898', '-83.650246', 213),
('100-1000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Rio restaurant2', '9.988160', '-83.650246', 214),
('100-1000', 'Urbano', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Catarata de aquiares2', '9.934907', '-83.695672', 215),
('100-1000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Catarata de aquiares2', '9.900898', '-83.690184', 216),
('5001-15000', 'Urbano', 'Negocio', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Eco villa turri2', '9.880187', '-83.650246', 217),
('5001-15000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Rio restaurant2', '10.017477', '-83.704463', 218),
('5001-15000', 'Rural', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Catarata de aquiares2', '9.900898', '-83.704463', 219),
('5001-15000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.988160', '-83.650246', 220),
('5001-15000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.880187', '-83.841373', 221),
('5001-15000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.988160', '-83.690184', 222),
('5001-15000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.934907', '-83.690184', 223),
('1001-5000', 'Urbano', 'Deportivo', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Catarata de aquiares2', '9.934907', '-83.690184', 224),
('100-1000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.934907', '-83.650246', 225),
('1001-5000', 'Rural', 'Familiar', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Eco villa turri2', '10.017477', '-83.650246', 226),
('1001-5000', 'Urbano', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Rio restaurant2', '9.880187', '-83.690184', 227),
('1001-5000', 'Rural', 'Familiar', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '10.017477', '-83.690184', 228),
('100-1000', 'Urbano', 'Cultural', 'El río Turrialba es un lugar para los más animados, para aquellos que les gusta las actividades acuáticas como el rafting. Estas actividades son pensadas para personas con buena condición física y con muchos ánimos.', 'Rio restaurant2', '9.880187', '-83.695672', 229),
('5001-15000', 'Rural', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Sanatorio Dúran2', '9.900898', '-83.650246', 230),
('100-1000', 'Rural', 'Deportivo', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Hacienda monte carlo2', '10.017477', '-83.650246', 231),
('100-1000', 'Urbano', 'Negocio', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Catarata de aquiares2', '9.934907', '-83.690184', 232),
('1001-5000', 'Rural', 'Cultural', 'Ingredientes de calidad y comida hecha con dedicación. Todo delicioso y la atención excelente. Comimos una hamburguesa que se llama Mante, exquisita.', 'Río Turrialba2', '9.988160', '-83.690184', 233),
('1001-5000', 'Urbano', 'Negocio', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Hacienda monte carlo2', '9.934907', '-83.690184', 234),
('5001-15000', 'Urbano', 'Deportivo', 'Este establecimiento de tipo alojamiento y desayuno está ubicado en el valle de Turrialba, a 10 minutos en coche del centro de la localidad. La Cascada tiene vistas impresionantes al volcán de Turrialba y cuenta con jardín amplio, servicio de tratamientos de masaje, paneles solares para calentar el agua y habitaciones y apartamentos con muebles de madera, suelo de baldosa, armario y baño privado con ducha', 'Catarata de aquiares2', '9.880187', '-83.704463', 235);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuario`
--

CREATE TABLE `usuario` (
  `email` varchar(60) NOT NULL,
  `nombre` varchar(30) NOT NULL,
  `edad` int(11) NOT NULL,
  `genero` varchar(1) NOT NULL,
  `password` varchar(30) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `usuario`
--

INSERT INTO `usuario` (`email`, `nombre`, `edad`, `genero`, `password`) VALUES
('fonso@gmail.com', 'fonsi', 12, '', '123'),
('alfonsobrenes08@gmail.com', 'Alfonso Brenes', 20, 'M', '1234'),
('mary@gmail.com', 'maria', 20, 'M', '123'),
('fonso@gimal.com', 'fonso', 32, 'F', '123'),
('fonso@gimal.com', 'fonso', 32, 'F', '123'),
('jona@gmail.com', 'jonathan', 24, 'M', 'jona'),
('jona@gmail.com', 'jonathan', 24, 'M', 'jona'),
('', 'fonso', 23, 'M', '123'),
('gringo@', 'gringo', 23, 'M', '1234'),
('email@1', 'alfonso1', 20, 'M', '1234'),
('gringo@', 'gringo', 23, 'M', '1234'),
('correo', 'gon', 25, 'M', 'gon'),
('arnoldo@', 'arnoldo', 25, 'H', '123'),
('nicole@gmail.com', 'nikk', 20, 'M', '123');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `sitios`
--
ALTER TABLE `sitios`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `sitios`
--
ALTER TABLE `sitios`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=236;COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
